### ISSUE TITLE
Sort button doesn't sort feed on alumni page vs Home

### ISSUE THREAD

**Issue by cwmiles** [SCCapstone/CampusConnect#238]
Again, this i'm testing using flight on iphone 12 (ios vs 16.3.1)
https://user-images.githubusercontent.com/70288320/231039825-727146e3-2107-4910-b419-691e4c4f3ebd.MOV

A few things to note here:
- the button works, and the list of posts is changing but i think the display is incorrect.
- for example, the sort by most commented shows the post with the most replies furthest at the bottom, which is opposite of what the home page post list does. 
- A similar issue is occurring in the 'Best' and 'Worst' sorts as well with the highest and lowest being shown at the bottom. (i don't think this is intentional)

**Comment by econnerty** [comment]
Yeah, good catch, but we fixed this on main... I forgot to push the code to the alumni page, which hasn't been patched. It's not gonna happen again because I've made the posts and alumni pages virtually clones in terms of functionality going forward, so they won't ever be out out of sync.

I have not updated the testflight binary, but rest assured that this is fixed.

**Comment by econnerty** [comment]
fixed by my two most recent commits 7a17619f3ec7bb21fcbb937e75b44f02e5cea27f 26b946ba8f2708a16059865c661c9a7d8db4cd21

**Comment by econnerty** [comment]
should have made a readme about this, sorry @cwmiles
